### ISSUE TITLE
Create way for user to add new students to "my students"

### ISSUE THREAD

**Issue by hannahkamundson** [codefordenver/gsn#123]

**Comment by sushrut111** [comment]
May I start working on this?

**Comment by HTempleman** [comment]
Hiya @sushrut111 ,
It's exciting that our project has attracted the attention from someone as far away as Warangel! Provided that you understand the goals of our project, I would certainly encourage you to create your own branch and begin working on some of the issues that we have posted. 

Once you believe that your code is ready to be merged with our master branch, we can begin an on-boarding process that should result in write privileges and code review. If you have any questions, or require any clarification, please don't hesitate to reach out to @hannahkamundson , @MrYetly , or myself!

**Comment by hannahkamundson** [comment]
-frontend complete
-backend complete

STILL NEED: redux
