### ISSUE TITLE
Containerize the development stack

### ISSUE THREAD

**Issue by dbarkelew** [codefordenver/gsn#26]
1. Design a container deployment that will setup PostgreSQL, Django API framework, and Netlify. 
2. Provide to team for feedback and changes
3. Document the process for others to follow to develop on.

The idea is to containerize the GSN project to address the following issues: 
- Eliminate environment related issues between development setups.
- Simplify delivery for ease of developing on latest version and easier testing by abstracting the application from the OS.
- Separate the front-end service, API service and Database service for modular development.
 
Flowdock conversation:
https://www.flowdock.com/app/cfa-brigades/gsn/threads/Wkd5SQHCHK8rynK8MA_UwGPA10O

**Comment by dbarkelew** [comment]
Tools being looked at to be used right now:
- Container host using Docker-Engine. OS should not matter but Ubuntu is probably the easiest to get Docker working on.
- Docker-compose for handling the template the build. (Can be a bit fiddlely. If something is not working, trying performing the same steps with the docker-client.)

**Comment by HTempleman** [comment]
Backend has been containerized. We'll get around to the frontend as needed.
