### ISSUE TITLE
Create MD5 hash function to prevent duplicate file uploads.

### ISSUE THREAD

**Issue by HTempleman** [codefordenver/gsn#34]
We need to ensure that people don't go uploading duplicate csv files all pell mell. Creating a table in the database that holds md5 hash function of our files would probably go a long way towards enforcing this!

**Comment by hannahkamundson** [comment]
Coordinate with "CSV Parser Input - Ensure entered data is not duplicate data" issue/task

**Comment by hannahkamundson** [comment]
Added it to Ivan's CSV upload view. Used SHA1 because of potential issues with MD5
