### ISSUE TITLE
Task Analysis / Feature Priority Activity

### ISSUE THREAD

**Issue by proberts3** [codefordenver/gsn#52]
Hi all,

Thanks for meeting again. Suggesting now that we have some initial user feedback we need to organize it into something actionable. If we can do some affinity diagramming for common themes then generate tasks / user flows from that it would go a long way to knowing what data we need to show and where.

A small group can take the raw notes and map out the themes and relationships in 30mins - 1hour if we don't want to put the burden on one person. Tasks and flows we would continue updating over time.

Questions, thoughts? I have experience and can help

**Comment by HTempleman** [comment]
Phillip,

An affinity diagram sounds like an excellent idea. I believe it's a task that will dovetail nicely with Ivan's transcription our recent focus group in Keenesburg.

**Comment by HTempleman** [comment]
I've added myself and Ivan to this task. I'll also contact Patrick, as I believe he would have some relevant thoughts on the matter.
