### ISSUE TITLE
Create Note Model

### ISSUE THREAD

**Issue by MrYetly** [codefordenver/gsn#54]
Create a model for the Note table in the schema with a dynamic foreign key for related_content_id.

**Comment by hannahkamundson** [comment]
Created the model & added GenericRelation to all other models. Need to ask if I need to modify serializers for all models & if I need to create a serializer for Note model

**Comment by hannahkamundson** [comment]
Added to all other models. Didn't add it to GradeForStudents url. Does it need to be added to that as well? If so, then how?

**Comment by hannahkamundson** [comment]
Should be complete. Only need to figure out how to add fixtures so we can test it & ensure everything looks right.
