### ISSUE TITLE
Create Bookmark Model

### ISSUE THREAD

**Issue by MrYetly** [codefordenver/gsn#55]
Create a model for the bookmark table in our schema.

**Comment by lrm25** [comment]
How's this?:

class Bookmark(models.Model):
    user_id = models.ForeignKey(
        User,
        on_delete = models.CASCADE
    )
    created = models.DateTimeField(default = timezone.now)
    url = models.CharField(max_length = 255)
    react_component_id = models.CharField(max_length = 255)
    json_request_data = models.TextField()

**Comment by hannahkamundson** [comment]
Got it working + serializer, view, and url. Now waiting to push to git

**Comment by hannahkamundson** [comment]
Finished model, serializer, url, and view. Two views: one for pulling all boomkars; another for pulling bookmark based on ID
