### ISSUE TITLE
Change "entry_datetime" representation in serializer.

### ISSUE THREAD

**Issue by HTempleman** [codefordenver/gsn#74]
Regarding the GradeSerializer, retitle the "entry_datetime" model field so that it reads "entry_date", likely through further implementation of the "to_representation" method.

**Comment by MrYetly** [comment]
Altered the grade serializer to inherit from BaseSerializer and use to_representation. 

```
class GradeSerializer(serializers.BaseSerializer):

    def to_representation(self, grade_obj):
        return {
            "Grade PK": grade_obj.id,
            "Student": grade_obj.student.id,
            "Course": grade_obj.course.id,
            "Calendar": grade_obj.calendar.id,
            "entry_date": grade_obj.entry_datetime,
            "Grade Value": grade_obj.grade,
            "Final Grade for Term": grade_obj.term_final_value,
        }

```
The serializer returns entry_date, but due to the setting of our django rest framework, this is translated to display as camel case: entryDate.
