### ISSUE TITLE
Include comment with GradeForStudent View explaining how to interact with it.

### ISSUE THREAD

**Issue by HTempleman** [codefordenver/gsn#75]
Taking a page from Moses over at Water Beacon. We need to cultivate the practice of pairing comments with views that should indicate how to make a request to a given API endpoint. 

Something in the vein of the following format:

```
# http POST http://127.0.0.1:8000/gsndb/student/someviewendpoint requestParameter="requestValue"

class SomeView(APIView):

   def post(self, request):
        """ Returns some response based on the requestValue proffered by the example request."""

```

**Comment by MrYetly** [comment]
like this?
`class GradeForStudent(APIView):
    """this view is currently linked to the url path
     /gsndb/gradeforstudent/<int:pk>/. It displays grade data for a student
     selected by the primary key entered into the last part of the endpoint.
     Ex: /gsndb/gradeforstudent/1 returnts grade data for the student with
     primary key 1 in the student table."""
    def get(self, request, pk, format = None):
        student_obj = Student.objects.filter(pk = pk)
        serializer = GradeForStudentSerializer(student_obj, many = True)
        return Response(serializer.data)`

**Comment by HTempleman** [comment]
I'd say that's a bit too verbose. Multiline comments are a best avoided within code when the code mostly speaks for itself, as is the case with an API view. In the example I provided, the intention is to simply demonstrate how to make a call to the endpoint. In that case, it used httpie, whose [documentation](https://httpie.org/doc) I neglected to provide! 

The following would suffice for the GradeForStudent view:
```
# http GET http://127.0.0.1:8000/gsndb/gradeforstudent/1
```

Any further explanation should reside in the README, and should be general in nature. We'll link to relevant pages in the Django REST documentation when necessary and let that do most of the heavy lifting.
