### ISSUE TITLE
Fix GradeForStudent endpoint on new_models branch

### ISSUE THREAD

**Issue by HTempleman** [codefordenver/gsn#79]
This appears to be a database problem. Error as follows:

```ERROR:  column gsndb_student.current_program_id does not exist at character 67```

This occurs when I fire off a request to the endpoint in the following fashion:

```http://localhost/gsndb/gradeforstudent/1```

My gut says it's a migrations issue, or maybe a problem with docker volumes. Hopefully it will be fixed by the end of the night.

**Comment by hannahkamundson** [comment]
Fixed itself
